---

- name: Ensure certificate folder exists
  file:
    path: /etc/pki/tls/certs
    state: directory


- name: Ensure Logz.io intermediate SSL certificate is present
  get_url:
    url: "https://raw.githubusercontent.com/logzio/public-certificates/master/COMODORSADomainValidationSecureServerCA.crt"
    dest: /etc/pki/tls/certs/COMODORSADomainValidationSecureServerCA.crt


- name: Ensure Elastic GPG key is added
  apt_key:
    url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    state: present


- name: Ensure Beats repository is added
  apt_repository:
    repo: "deb https://packages.elastic.co/beats/apt stable main"
    update_cache: yes
    state: present


- name: Ensure Filebeat is installed
  apt:
    name: filebeat
    state: present


- name: Ensure Filebeat is configured
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify: restart filebeat


- name: Ensure Filebeat is started and enabled on boot
  service:
    name: filebeat
    enabled: yes
    state: started
